### PR TITLE
add lots of program and put some files to Others folder

### PR DESCRIPTION
**Pull request by pinitik1906**
don't worry, I just put some files to Others folder, and I added new 2 folders to make it organized and not making a mess. I changed a link location in readme.md since I renamed it from `games` to `Games`.

and here are the lists that I have added:

- `thunar`
- `pcmanfm` and `pcmanfm-qt`
- `nautilus`
- `dolphin`
- `krita`
- `sxiv` and `nsxiv`
- `mupdf`
- `newsboat`
- `dmenu`
- `fuzzel`
- `bemenu`
- `xcolor`
- `wl-color-picker` and `wl-delicolour-picker`
- `hyprpicker`

### CODE REVIEW

**Comment by 1Naim** [comment]
I'm a bit skeptical on adding too much applications to the ruleset here. At some point the rules will become useless because every well known app will have an entry which makes niceness of `-4` the new "norm" (because everything else is also -4 or lower). We should focus on just adding apps that clearly and theoretically benefit from having a lower nice value.

With that in mind, I don't see how the apps that you've added here benefits from having a lower nice value. Do you really need a higher priority to pick some colors? (wl-color-picker)

**Comment by pinitik1906** [comment]
so in that case then, I should remove some "doesn't need too much horsepower" programs. thanks for the notice.

sorry for that inconvenience of me, I will do it tomorrow by afternoon

**Comment by 1Naim** [comment]
> I will do it tomorrow by afternoon

Thanks. Could you also separate what you're doing to numerous smaller commits? The PR that you have submitted right now is not acceptable at its current state as it is changing too much in only one commit. Separating it into smaller commits, e.g.:
a. Add App 1
b. Add App 2
c. Move x to y

will not only make it easier to review during PR or when checking the commit history, it also helps keep things tidy and more easily documentable.

**Comment by pinitik1906** [comment]
i think this pull request might be considered as kinda dumb for me

**Pull request closed without merging**
