### PR TITLE
Add vesktop(alternative discord app) to chats.rules

### PR DESCRIPTION
**Pull request by Hecos1**
adds a rule for vesktop(custom discord client with vencord)

### CODE REVIEW

**Comment by ptr1337** [comment]
Are you sure the process is named like this?

**Comment by aarrayy** [comment]
Process name is not the correct one, it should be "vesktop" although ananicy is not capable on grabbing every subprocess only a few

**Comment by Hecos1** [comment]
> Are you sure the process is named like this?

That's the name that shows up on the system monitor, at least on the flatpak version

**Comment by ptr1337** [comment]
image
I think we need to add multiple process names.

e.G electron, vesktop.bin

**Comment by NextWork123** [comment]
> image I think we need to add multiple process names.
> 
> e.G electron, vesktop.bin

nah,that pull is good only for the flatpak version and you can't put a rule for electron in general because you can execute multiple software with electron.

**Pull request merged**
