### PR TITLE
New rules

### PR DESCRIPTION
**Pull request by Ave356**

### CODE REVIEW

**Comment by aarrayy** [comment]
Is the name of totalwarhammer correct? i've seen that their .exe is named "Warhammer3.exe"

**Comment by Ave356** [comment]
> Is the name of totalwarhammer correct? i've seen that their .exe is named "Warhammer3.exe"

That rule is just for the Linux version of the game. I couldn't get the proton version to launch, so I'm not sure what its name is.

**Comment by aarrayy** [comment]
I see, then add it to steam-native ruleset and should be all ready to merge

**Comment by aarrayy** [comment]
But don't worry, i'll do it , thanks for the suggestions

**Pull request merged**
