### PR TITLE
Update ananicy.conf

### PR DESCRIPTION
**Pull request by Optiligence**
add loglevel to avoid journal spam for ananicy-cpp add explanation for differences in how these settings apply for ananicy and ananicy-cpp comment upstream defaults
convert_latnice was removed upstream (17e9a346)

### CODE REVIEW

**Comment by vnepogodin** [comment]
Disabling everything will make ananicy-cpp useless, also loglevel would be no longer needed as ananicy-cpp will be doing simply nothing

**Comment by vnepogodin** [comment]
Closing

**Comment by Optiligence** [comment]
@vnepogodin nothing is set to `false` and the default in-code is `true`. 
Commenting defaults just makes it easier to see what’s changed by the user.

**Comment by Optiligence** [comment]
@vnepogodin can you reevaluate closing this?

**Comment by ptr1337** [comment]
These rules are explicity thought for `ananicy-cpp` and not `ananicy`.
For ananicy there are already tons of rules out there. @vnepogodin is the developer of `ananicy-cpp`

**Comment by Optiligence** [comment]
@ptr1337 this is relevant to what specifically?

**Pull request closed without merging**
